# Generated by Django 4.1.11 on 2024-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recoveryCode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
