# Generated by Django 4.1.11 on 2024-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprofile_recoverycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recoveryCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
