# Generated by Django 4.1.11 on 2024-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_userprofile_recoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
