# Generated by Django 4.2.16 on 2024-09-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ticket_remove_note_user_remove_userprofile_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile'),
        ),
    ]
