# Generated by Django 4.2.16 on 2024-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_ticket_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
