# Generated by Django 4.2.16 on 2024-10-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
