# Generated by Django 4.2.16 on 2024-10-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_secret_remove_userprofile_user_delete_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secret',
            name='expirationDate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='isOnce',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
