# Generated by Django 4.2.16 on 2024-10-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_isonce_secret_isonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='uri',
            field=models.CharField(max_length=64),
        ),
    ]
